set(SIMULATION_SUBPROJECT_NAME "coulomb_law_simulation" CACHE INTERNAL "")

message(STATUS "Configuring simulation subproject: ${SIMULATION_SUBPROJECT_NAME}")

add_executable(${SIMULATION_SUBPROJECT_NAME}
    "main.cpp"
    "particle.hpp"
    "particle.cpp"
    "simulation.hpp"
    "simulation.cpp"
)

target_link_libraries(${SIMULATION_SUBPROJECT_NAME}
    PRIVATE
        ${CORE_LIB_NAME}
)

set_target_properties(${SIMULATION_SUBPROJECT_NAME} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${SIMULATION_SUBPROJECT_NAME}"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${SIMULATION_SUBPROJECT_NAME}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${SIMULATION_SUBPROJECT_NAME}"
)

foreach(OUTPUTCONFIG IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG_UPPER)
    set_target_properties(${SIMULATION_SUBPROJECT_NAME} PROPERTIES
        ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${SIMULATION_SUBPROJECT_NAME}"
        LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${SIMULATION_SUBPROJECT_NAME}"
        RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${SIMULATION_SUBPROJECT_NAME}"
    )
endforeach()

# target_compile_options(Simulation PRIVATE
#     $<$<CONFIG:RelWithDebInfo>:/Od /Zi /UNDEBUG>
# )

add_custom_command(
    TARGET ${SIMULATION_SUBPROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_SOURCE_DIR}/src/fonts" "$<TARGET_FILE_DIR:${SIMULATION_SUBPROJECT_NAME}>/fonts"
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_SOURCE_DIR}/src/models" "$<TARGET_FILE_DIR:${SIMULATION_SUBPROJECT_NAME}>/models"
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_SOURCE_DIR}/src/shaders" "$<TARGET_FILE_DIR:${SIMULATION_SUBPROJECT_NAME}>/shaders"
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_SOURCE_DIR}/src/textures" "$<TARGET_FILE_DIR:${SIMULATION_SUBPROJECT_NAME}>/textures"
)

set_target_compile_options(${SIMULATION_SUBPROJECT_NAME})