set(RAY_TRACING_SUBPROJECT_NAME "ray_tracing" CACHE INTERNAL "")

message(STATUS "Configuring ray tracing subproject: ${RAY_TRACING_SUBPROJECT_NAME}")

add_executable(${RAY_TRACING_SUBPROJECT_NAME}
    "main.cpp"
    "ray_tracing.cpp"
    "ray_tracing.hpp"
)

target_link_libraries(${RAY_TRACING_SUBPROJECT_NAME} PRIVATE ${CORE_LIB_NAME})

set_target_properties(${RAY_TRACING_SUBPROJECT_NAME} PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${RAY_TRACING_SUBPROJECT_NAME}"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${RAY_TRACING_SUBPROJECT_NAME}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}/${RAY_TRACING_SUBPROJECT_NAME}"
)

foreach(OUTPUTCONFIG IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG_UPPER)
    set_target_properties(${RAY_TRACING_SUBPROJECT_NAME} PROPERTIES
        ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${RAY_TRACING_SUBPROJECT_NAME}"
        LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${RAY_TRACING_SUBPROJECT_NAME}"
        RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG_UPPER} "${CMAKE_BINARY_DIR}/${OUTPUTCONFIG}/${RAY_TRACING_SUBPROJECT_NAME}"
    )
endforeach()

set_target_compile_options(${RAY_TRACING_SUBPROJECT_NAME})