name: Build ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: microsoft/vcpkg-action@v7
        with:
          runVcpkgInstall: true
          vcpkgTriplet: x64-linux
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel -j $(nproc)