name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VCPKG_ROOT: ${{github.workspace}}/build-workspace/vcpkg

jobs:
  build:
    name: ${{github.workflow}}-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare workspace
        run: |
          mkdir -p ${{github.workspace}}/build-workspace
          rsync -a ${{github.workspace}}/.github/vcpkg.json ${{github.workspace}}/build-workspace/
          rsync -a --exclude '.github/' ${{github.workspace}}/* ${{github.workspace}}/build-workspace/

      - uses: lukka/get-cmake@latest

      - name: Install GCC 13
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libx11-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libfmt-dev \
          libglu1-mesa-dev \
          pkg-config

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{github.workspace}}/.github/vcpkg' 

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{github.workspace}}/build-workspace/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"